apiVersion: apps/v1
kind: Deployment
metadata:
  name: fb
spec:
  selector:
    matchLabels:
      app: fb
  replicas: 1
  template:
    metadata:
      labels:
        app: fb
    spec:
      containers:
      - name: fb
        image: okteto.dev/fastapi-background:latest
        ports:
        - containerPort: 8000